sudo: required
language: node_js 
node_js: 
  - "9"
services:
  - docker

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
#  - docker build -t $DOCKER_ID/react-test -f ./client/Dockerfile.dev ./client

#script: 
#  - docker run -e CI=true $DOCKER_ID/react-test npm run test

#after_success:
script:
  - docker build -t $DOCKER_ID/cmchat-client ./client
  - docker tag $DOCKER_ID/cmchat-client registry.heroku.com/$HEROKU_APP_CLIENT/web;

deploy:
  provider: script
  script: 
    #docker push $DOCKER_ID/cmchat-client;
    docker push registry.heroku.com/$HEROKU_APP_CLIENT/web;
    heroku container:release web --app $HEROKU_APP_CLIENT;
  on:
    branch: feature-docker
